### ISSUE TITLE
Preview aborts with error

### ISSUE THREAD

**Issue by wichert** [euphorie/Euphorie#14]
```
 Traceback (innermost last):

     * Module ZPublisher.Publish, line 239, in publish_module_standard
     * Module ZPublisher.Publish, line 166, in publish
     * Module plone.app.linkintegrity.monkey, line 21, in
 zpublisher_exception_hook_wrapper
     * Module Zope2.App.startup, line 214, in __call__
     * Module grokcore.view.components, line 63, in __call__
     * Module grokcore.view.components, line 67, in _render_template
     * Module five.grok.components, line 134, in render
     * Module five.pt.patches, line 148, in pt_render
     * Module z3c.pt.pagetemplate, line 242, in __call__
     * Module z3c.pt.pagetemplate, line 262, in __call__
     * Module z3c.pt.pagetemplate, line 136, in render
     * Module chameleon.core.template, line 394, in render
     * Module chameleon.zpt.template, line 17, in render
     * Module chameleon.core.template, line 221, in render
     * Module chameleon.core.template, line 374, in cook_and_render
     * Module chameleon.core.template, line 205, in cook_and_render
       __traceback_info__: (<GrokViewAwarePageTemplateFile
 /home/zope/.buildout/eggs/NuPlone-1.0rc7-py2.6.egg/plonetheme/nuplone/skin/templates/error_generic.pt>,)
     * Module <string>, line 70, in render
     * Module chameleon.core.template, line 420, in render
     * Module chameleon.zpt.template, line 22, in render_macro
     * Module chameleon.core.template, line 231, in render_macro
     * Module chameleon.core.template, line 374, in cook_and_render
     * Module chameleon.core.template, line 205, in cook_and_render
       __traceback_info__: (<GrokViewAwarePageTemplateFile
 /home/zope/.buildout/eggs/NuPlone-1.0rc7-py2.6.egg/plonetheme/nuplone/skin/templates/layout.pt>,)
     * Module <string>, line 472, in render
     * Module plonetheme.nuplone.tiles.tales, line 17, in _lookup_tile
     * Module plonetheme.nuplone.tiles.messages, line 15, in __call__
     * Module plonetheme.nuplone.tiles.messages, line 9, in update
     * Module plonetheme.nuplone.adapter, line 64, in show

 TypeError: sanitize() got an unexpected keyword argument 'wrap'
```

This was caused by commit 1df5593a4b1c37f8354d664d7fd05b7865579ff1 from Jan-Carel on April 15. @jcbrand: can you explain the reasoning behind that commit, and why it does not break for you? You seem to be relying on an option for htmllaundry's sanitize that does not exist.
